on:
  pull_request:
jobs:
  dotnet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Lint
        uses: wearerequired/lint-action@v2.3.0
        with:
          dotnet_format: true
          workspace: pirates.sln